[package]
name = "myscreen-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.2"
raw-window-handle = "0.6"
sysinfo = "0.39.6"
tray-icon = "0.26.0"
tungstenite = "0.30.0"
wasapi = "0.25.0"
windows-sys = { version = "0.59", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
winreg = "0.56.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
